# Generated by Django 5.0.3 on 2024-03-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
