# Generated by Django 5.0.3 on 2024-04-27 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_response_is_correct'),
        ('quiz', '0004_alter_quiz_max_number_alter_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='participation',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='user_responses', to='quiz.participation'),
            preserve_default=False,
        ),
    ]
