# Generated by Django 5.0.3 on 2024-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_userresponse_user_userresponse_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
