# Generated by Django 5.0.3 on 2024-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_number',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('Canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
