# Generated by Django 5.0.3 on 2024-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_max_number_quiz_status_alter_quiz_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='max_number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
