# Generated by Django 5.0.3 on 2024-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_max_number_alter_quiz_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='max_number',
        ),
    ]
