# Generated by Django 5.0.3 on 2024-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_max_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='test', max_length=14),
            preserve_default=False,
        ),
    ]
