# Generated by Django 5.0.3 on 2024-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
